version: "3"
services:
  app:
    build:
      context: .
      dockerfile: tests/Dockerfile
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    logging:
      driver: "none"
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Just4TestingThis
      MSSQL_PID: Express
    ports:
      - 1433:1433